apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: doks-debug
  namespace: ambient-demo
  labels:
    app: doks-debug
spec:
  selector:
    matchLabels:
      name: doks-debug
  template:
    metadata:
      labels:
        name: doks-debug
      annotations:
        clusterlint.digitalocean.com/disabled-checks: "hostpath-volume"
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      dnsPolicy: ClusterFirst
      tolerations:
      - operator: Exists
      containers:
      - name: doks-debug
        securityContext:
          privileged: true
        image: digitalocean/doks-debug:latest
        command: [ "sleep", "infinity" ]
        resources:
          requests:
            memory: "0"
            cpu: "0"
          limits:
            memory: "500Mi"
            cpu: "500m"
      terminationGracePeriodSeconds: 0
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate