---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-1
  namespace: ambient-demo
  labels:
    app: httpbin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      serviceAccountName: httpbin-sa-1
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-1
  namespace: ambient-demo
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Change to NodePort if LoadBalancer is not supported
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin-sa-1
  namespace: ambient-demo
  labels:
    account: httpbin-1
